### PR TITLE
Use uploaded file name as suggested download name

### PR DESCRIPTION
**Pull request by georapbox**
Fixes issue #40

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks for tackling this! `<3` 

Could you factor out the suggested file name creation logic into its own function and then call it whenever we get a file (see this [search result](https://github.com/tomayac/SVGcode/search?q=set%28FILE_HANDLE)). We can extract a file name from dropped files, too, apart from opened files, but at the moment your code purely looks at opened files. You should probably also specify the `.svg` extension to be on the safe side. Almost there `:-)`!

**Comment by georapbox** [comment]
Ooops! I didn't notice that the file handle was saved in IndexedDB. Do you prefer to create a function that gets the file handle in the `filesystem.js` module and also export it so that it's available to other modules for future use potentially?

Regarding the `.svg` extension being on the safe side, do you mean not to remove it all? Because if I do so, and the user uploads a SVG file, when saving it, they would end up with something like this `filename.svg.svg`. Unless it's not what you mean 😅 .

**Comment by tomayac** [comment]
> Ooops! I didn't notice that the file handle was saved in IndexedDB. Do you prefer to create a function that gets the file handle in the `filesystem.js` module and also export it so that it's available to other modules for future use potentially? Or just something like that `const file = await get(FILE_HANDLE);` to get the file is enough?

It probably makes sense to export it for future use, since potentially pasted files will get a handle, too. 

> Regarding the `.svg` extension being on the safe side, do you mean not to remove it all? Because if I do so, and the user uploads a SVG file, when saving it, they would end up with something like this `filename.svg.svg`. Unless it's not what you mean 😅 .

Sorry, I meant the following:

1. User uploads `cat.png`.
2. The suggested file name becomes `'cat' + '.svg'`.

**Comment by georapbox** [comment]
Made the change to get file handle from `indexedDB`. Not sure about the naming of the exported function though 😅.
If this is an accepted solution, there is a reference of `await get(FILE_HANDLE)` [here](https://github.com/tomayac/SVGcode/blob/main/src/js/ui.js#L371) that could be factored to utilize this new function.

**Comment by tomayac** [comment]
Sorry, I guess this was confusing. My proposal was:

```js
const getSuggestedFileName = (handle) => {
  // …
};
```

You would then export this function, so it can be used everywhere we have a handle. The `await get(FILE_HANDLE)` can just stay like that `:-)`.

**Comment by georapbox** [comment]
Cool! No worries! I'll update the PR.

**Comment by tomayac** [comment]
Thanks, I'll release this in a moment!

**Pull request merged**
