### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by pepelsbey**
Happy to help! 👋

Though it won’t be as easy as with other languages, I guess.

1. I need to better understand what certain options do, to better translate them, see below.
2. Some words needs to be inflected for proper grammar: _1 шаг_, _2 шага_, _5 шагов_ (1, 2, 5 steps). There is a lazy way of solving this: _шаги: 1, 2, 5_ (steps: 1, 2, 5), but requires some changes in templates too. Who knows, maybe there’s something in [Intl.PluralRules()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules) that might help.
3. I wouldn’t specify country next to the language because Russian is multinational language. Also, ruRU doesn’t make much sense since AFAIK there are no other ru*.
4. I intentionally kept original En strings in comments to ask some people from Russian community to review my translation.

Options that are unclear to me:

- alphamax: Corner Threshold
- minPathSegments: Min. Path Length
- turnpolicy: Turn Policy
- opttolerance: Optimisation Tolerance

I’d also suggest to rename keys in the single manner, probably camel-case:

- 'hue-rotate' — hueRotate
- turnpolicy — turnPolicy
- opticurve — optiCurve
- opttolerance — optTolerance (or optiTolerance?)

I can file a separate issue if you’d like.

### CODE REVIEW

**Comment by tomayac** [comment]
> Happy to help! 👋

Thanks `<3`!

> 2. Some words needs to be inflected for proper grammar: _1 шаг_, _2 шага_, _5 шагов_ (1, 2, 5 steps). There is a lazy way of solving this: _шаги: 1, 2, 5_ (steps: 1, 2, 5), but requires some changes in templates too. Who knows, maybe there’s something in [Intl.PluralRules()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules) that might help. Note that for now I don't even do this right for English (_1 Steps_). Can you, for now, roll with  _шага_ or _шагов_ (the one that is less wrong the majority of the time) and we deal with solving this properly in a new PR that would fix the newly created https://github.com/tomayac/SVGcode/issues/62? It indeed looks like [`IntlPluralRules`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules#using_options) could help here. 

> 3. I wouldn’t specify country next to the language because Russian is multinational language. Also, ruRU doesn’t make much sense since AFAIK there are no other ru*.

I will remove the countries where they don't make sense. For now, can you leave it as is? I will deal with this in a separate PR that fixes https://github.com/tomayac/SVGcode/issues/63.

> 4. I intentionally kept original En strings in comments to ask some people from Russian community to review my translation.

Makes sense.


> Options that are unclear to me:
> 
> * alphamax: Corner Threshold
> * minPathSegments: Min. Path Length
> * turnpolicy: Turn Policy
> * opttolerance: Optimisation Tolerance

See the [Potrace documentation](http://potrace.sourceforge.net/potrace.1.html#:~:text=disabled.%20Implies%20%2D%2Dopaque.-,Algorithm%20options%3A,-For%20more%20detailed) for details.

> I’d also suggest to rename keys in the single manner, probably camel-case:
> 
> * 'hue-rotate' — hueRotate
> * turnpolicy — turnPolicy
> * opticurve — optiCurve
> * opttolerance — optTolerance (or optiTolerance?)

They are named the way Potrace names them. It's on purpose (but correct, it's inconsistent).

**Comment by tomayac** [comment]
You will notice that I have dealt with #63 and have adapted the PR accordingly. This will make your life a little easier.

**Comment by Marat-Tanalin** [comment]
> Some words needs to be inflected for proper grammar: 1 шаг, 2 шага, 5 шагов (1, 2, 5 steps).

Fwiw, there is a [table](https://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html) with compact plural-form algorithms for multiple languages.

**Comment by Zulcom** [comment]
I am Russian native speaker and can confirm that this translations is correct, thanks @pepelsbey

**Comment by tomayac** [comment]
Thank you all! `<3` I think this can be merged in the current shape. Fine with you, @pepelsbey? 

I will deal with the plural rules in #62, so for now let's just go with the plural form of "steps".

**Comment by tomayac** [comment]
Thank you all for collaborating on this! `<3`

**Pull request merged**
